#ifndef DRAWING_PROGRAM_LIFECYCLE_TEXTURE_WORKSPACE_SUITE_H
#define DRAWING_PROGRAM_LIFECYCLE_TEXTURE_WORKSPACE_SUITE_H

#include "drawing_program/drawing_program_app_main.h"

int drawing_program_lifecycle_run_texture_workspace_suite(DrawingProgramAppContext *ctx);

#endif
