#ifndef DRAWING_PROGRAM_LIFECYCLE_OBJECT_PATH_HISTORY_SUITE_H
#define DRAWING_PROGRAM_LIFECYCLE_OBJECT_PATH_HISTORY_SUITE_H

#include "drawing_program/drawing_program_app_main.h"

int drawing_program_lifecycle_run_object_path_history_suite(DrawingProgramAppContext *workflow_ctx);

#endif
