#ifndef DRAWING_PROGRAM_LIFECYCLE_RUNTIME_PATH_POINTER_SUITE_H
#define DRAWING_PROGRAM_LIFECYCLE_RUNTIME_PATH_POINTER_SUITE_H

#include "drawing_program/drawing_program_app_main.h"

int drawing_program_lifecycle_run_runtime_path_pointer_suite(DrawingProgramAppContext *workflow_ctx);

#endif
