#ifndef DRAWING_PROGRAM_UI_CONTROLS_H
#define DRAWING_PROGRAM_UI_CONTROLS_H
#include "drawing_program_app_main.h"
#include "kit_ui_surface.h"
#include <SDL2/SDL.h>
/* Operation tags are persistent host meaning; do not renumber existing values.
 * Dynamic values are domain IDs, never visible row offsets. */
enum DrawingProgramUiOperation {
  DRAWING_UI_RIGHT_PANEL_COLOR_RENDER_SAVE_BUTTON_RECT = 101,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_NEW_PROJECT_BUTTON = 102,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_OPEN_PROJECT_BUTTON = 103,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_SAVE_PROJECT_BUTTON = 104,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_SAVE_AS_BUTTON = 105,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_LOAD_PROJECT_BUTTON = 106,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_PICK_INPUT_ROOT_BUTTON = 107,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_SAVE_SESSION_BUTTON = 108,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_RELOAD_SESSION_BUTTON = 109,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_ADD_BUTTON = 110,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_RENAME_BUTTON = 111,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_MOVE_BUTTON = 112,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_WORKSPACE_BUTTON = 113,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_BROWSER_SCENES_TAB = 114,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_BROWSER_OBJECTS_TAB = 115,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_PICK_SCENE_ROOT_BUTTON = 116,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_OPEN_OBJECT_BUTTON = 117,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_PICK_OUTPUT_ROOT_BUTTON = 118,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_EXPORT_INTENT_BUTTON = 119,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_OVERLAY_MATERIAL_INTENT_BUTTON = 120,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_EXPORT_PNG_BUTTON = 121,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_EXPORT_TEXTURES_BUTTON = 122,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_EXPORT_ICONSET_BUTTON = 123,
  DRAWING_UI_RIGHT_PANEL_FILE_TABS_RENDER_EXPORT_ICNS_BUTTON = 124,
  DRAWING_UI_RIGHT_PANEL_RENDER_TAB_CANVAS = 125,
  DRAWING_UI_RIGHT_PANEL_RENDER_TAB_LAYER = 126,
  DRAWING_UI_RIGHT_PANEL_RENDER_TAB_COLOR = 127,
  DRAWING_UI_RIGHT_PANEL_RENDER_TAB_FILE = 128,
  DRAWING_UI_RIGHT_PANEL_RENDER_TAB_ASSET = 129,
  DRAWING_UI_RIGHT_PANEL_RENDER_TAB_EXPORT = 130,
  DRAWING_UI_RIGHT_PANEL_RENDER_ADD_SURFACE_BUTTON = 131,
  DRAWING_UI_RIGHT_PANEL_RENDER_DUPLICATE_SURFACE_BUTTON = 132,
  DRAWING_UI_RIGHT_PANEL_RENDER_CANVAS_MODE_BUTTON = 133,
  DRAWING_UI_RIGHT_PANEL_RENDER_CANVAS_GUIDE_BUTTON = 134,
  DRAWING_UI_RIGHT_PANEL_RENDER_REFLECT_HORIZONTAL_BUTTON = 135,
  DRAWING_UI_RIGHT_PANEL_RENDER_REFLECT_VERTICAL_BUTTON = 136,
  DRAWING_UI_RIGHT_PANEL_RENDER_CENTER_PICK_BUTTON = 137,
  DRAWING_UI_RIGHT_PANEL_RENDER_CENTER_RESET_BUTTON = 138,
  DRAWING_UI_RIGHT_PANEL_RENDER_REFLECTOR_ADD_BUTTON = 139,
  DRAWING_UI_RIGHT_PANEL_RENDER_REFLECTOR_CYCLE_BUTTON = 140,
  DRAWING_UI_RIGHT_PANEL_RENDER_REFLECTOR_TOGGLE_BUTTON = 141,
  DRAWING_UI_RIGHT_PANEL_RENDER_REFLECTOR_DELETE_BUTTON = 142,
  DRAWING_UI_RIGHT_PANEL_RENDER_DELETE_CANVAS_BUTTON = 143,
  DRAWING_UI_RIGHT_PANEL_RENDER_SELECT_CANVAS = 144,
  DRAWING_UI_RIGHT_PANEL_RENDER_RESET_LAYOUT_BUTTON = 145,
  DRAWING_UI_RIGHT_PANEL_RENDER_RESET_VIEW_BUTTON = 146,
  DRAWING_UI_RIGHT_PANEL_RENDER_CLEAR_CANVAS_BUTTON = 147,
  DRAWING_UI_RIGHT_PANEL_RENDER_CLEAR_OBJECTS_BUTTON = 148,
  DRAWING_UI_RIGHT_PANEL_RENDER_DELETE_SELECTION_BUTTON = 149,
  DRAWING_UI_RIGHT_PANEL_RENDER_CLEAR_HISTORY_BUTTON = 150,
  DRAWING_UI_RIGHT_PANEL_RENDER_SELECT_LAYER = 151,
  DRAWING_UI_RIGHT_PANEL_RENDER_ADD_LAYER = 152,
  DRAWING_UI_RIGHT_PANEL_RENDER_DUPLICATE_SELECTED = 153,
  DRAWING_UI_RIGHT_PANEL_RENDER_AUTO_ROLE_NAME = 154,
  DRAWING_UI_RIGHT_PANEL_RENDER_DELETE_SELECTED = 155,
  DRAWING_UI_RIGHT_PANEL_RENDER_ACTIVE_PREV = 156,
  DRAWING_UI_RIGHT_PANEL_RENDER_ACTIVE_NEXT = 157,
  DRAWING_UI_RIGHT_PANEL_RENDER_MOVE_UP = 158,
  DRAWING_UI_RIGHT_PANEL_RENDER_MOVE_DOWN = 159,
  DRAWING_UI_RIGHT_PANEL_RENDER_ACTIVE_VISIBLE_VISIBLE_ON_VISIBLE_OFF = 160,
  DRAWING_UI_RIGHT_PANEL_RENDER_ACTIVE_LOCKED_LOCK_ON_LOCK_OFF = 161,
  DRAWING_UI_RIGHT_PANEL_RENDER_ROLE_BUTTON_RECT = 162,
  DRAWING_UI_PANEL_RENDER_TAB_TOOLS = 163,
  DRAWING_UI_PANEL_RENDER_TAB_OBJECTS = 164,
  DRAWING_UI_PANEL_RENDER_STROKE_COLOR_ROW = 165,
  DRAWING_UI_PANEL_RENDER_FILL_COLOR_ROW = 166,
  DRAWING_UI_PANEL_RENDER_MINUS_RECT = 167,
  DRAWING_UI_PANEL_RENDER_PLUS_RECT = 168,
  DRAWING_UI_PANEL_RENDER_FILL_ROW = 169,
  DRAWING_UI_PANEL_RENDER_WIDTH_MINUS_RECT = 170,
  DRAWING_UI_PANEL_RENDER_WIDTH_PLUS_RECT = 171,
  DRAWING_UI_PANEL_RENDER_HEIGHT_MINUS_RECT = 172,
  DRAWING_UI_PANEL_RENDER_HEIGHT_PLUS_RECT = 173,
  DRAWING_UI_PANEL_RENDER_PATH_ROW = 174,
  DRAWING_UI_PANEL_RENDER_OPTION_ROW = 175,
  DRAWING_UI_PANEL_RENDER_VALUE_RECT = 176,
  DRAWING_UI_FILE_PROJECT_SLOT = 177,
  DRAWING_UI_FILE_INDEXED_CELL = 178,
  DRAWING_UI_FILE_SCENE_ENTRY = 179,
  DRAWING_UI_AUTHORING_ACTION = 180,
  DRAWING_UI_AUTHORING_FONT_THEME = 181,
  DRAWING_UI_LEFT_TOOL = 182,
  DRAWING_UI_LEFT_OBJECT = 183,
  DRAWING_UI_PANE_HEADER_LAYOUT = 300,
  DRAWING_UI_PANE_HEADER_FIT = 301,
};
const KitUiSurface *drawing_program_ui_controls_snapshot(void);
void drawing_program_ui_controls_reset(void);
CoreResult
drawing_program_ui_controls_begin(const DrawingProgramAppContext *app);
CoreResult drawing_program_ui_controls_end(SDL_Renderer *renderer);
void drawing_program_ui_controls_key(uint32_t operation, uint64_t identity,
                                     int enabled);
uint64_t drawing_program_ui_controls_string_id(const char *text);
void drawing_program_ui_controls_button(SDL_Renderer *renderer, SDL_Rect clip,
                                        SDL_Rect rect, KitUiButtonSpec *spec);
void drawing_program_ui_controls_invalidate(void);
/* Available only after a successful activation in the current route call. */
KitUiSurfaceKey drawing_program_ui_controls_last_activation(void);
/* Returns ownership; activation resolves to current visible bounds only. */
int drawing_program_ui_controls_route(const DrawingProgramAppContext *app,
                                      const SDL_Event *event, int x, int y,
                                      int *activated_x, int *activated_y,
                                      int *activated);
#endif
