#ifndef DRAWING_PROGRAM_VISUAL_RIGHT_PANEL_DEFS_H
#define DRAWING_PROGRAM_VISUAL_RIGHT_PANEL_DEFS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum VisualRightPanelSlot {
    VISUAL_RIGHT_PANEL_SLOT_CANVAS = 0,
    VISUAL_RIGHT_PANEL_SLOT_LAYER = 1,
    VISUAL_RIGHT_PANEL_SLOT_COLOR = 2,
    VISUAL_RIGHT_PANEL_SLOT_FILE = 3,
    VISUAL_RIGHT_PANEL_SLOT_ASSET = 4,
    VISUAL_RIGHT_PANEL_SLOT_EXPORT = 5,
    VISUAL_RIGHT_PANEL_SLOT_COUNT = 6
} VisualRightPanelSlot;

enum {
    VISUAL_RIGHT_PANEL_FILE_TAB_ACTION_COUNT = 8,
    VISUAL_RIGHT_PANEL_FILE_TAB_FOOTER_LINE_COUNT = 4,
    VISUAL_RIGHT_PANEL_ASSET_TAB_ACTION_COUNT = 2,
    VISUAL_RIGHT_PANEL_ASSET_TAB_FOOTER_LINE_COUNT = 4,
    VISUAL_RIGHT_PANEL_EXPORT_TAB_ACTION_COUNT = 7,
    VISUAL_RIGHT_PANEL_EXPORT_TAB_FOOTER_LINE_COUNT = 6
};

#ifdef __cplusplus
}
#endif

#endif
