BUILD_DIR := build
TARGET_BUILD_DIR := $(BUILD_DIR)/targets/$(TARGET_TRIPLE)
HOST_TEST_DIR := $(TARGET_BUILD_DIR)/host/tests
TEST_OBJ_DIR := $(HOST_TEST_DIR)/obj
TEST_BIN_DIR := $(HOST_TEST_DIR)/bin
PROGRAM_BUILD_DIR := $(TARGET_BUILD_DIR)/toolchains/$(BUILD_TOOLCHAIN)
PROGRAM_OBJ_DIR := $(PROGRAM_BUILD_DIR)/obj
PROGRAM_BIN_DIR := $(PROGRAM_BUILD_DIR)/bin
PROGRAM_CC_STAMP := $(PROGRAM_BUILD_DIR)/compiler.stamp
SHARED_BUILD_DIR := $(TARGET_BUILD_DIR)/shared

ifeq ($(BUILD_TOOLCHAIN),clang)
PROGRAM_CC := $(HOST_CC)
PROGRAM_CC_DEP :=
else ifeq ($(BUILD_TOOLCHAIN),fisics)
PROGRAM_CC := $(FISICS_CC)
PROGRAM_CC_DEP := $(FISICS_CC)
else
$(error Unsupported BUILD_TOOLCHAIN '$(BUILD_TOOLCHAIN)'; expected clang or fisics)
endif

ifneq ($(filter $(PACKAGE_TOOLCHAIN),clang fisics),$(PACKAGE_TOOLCHAIN))
$(error Unsupported PACKAGE_TOOLCHAIN '$(PACKAGE_TOOLCHAIN)'; expected clang or fisics)
endif

DIST_DIR := dist
PACKAGE_APP_NAME := sketCh.app
PACKAGE_APP_DIR := $(DIST_DIR)/$(PACKAGE_APP_NAME)
PACKAGE_CONTENTS_DIR := $(PACKAGE_APP_DIR)/Contents
PACKAGE_MACOS_DIR := $(PACKAGE_CONTENTS_DIR)/MacOS
PACKAGE_RESOURCES_DIR := $(PACKAGE_CONTENTS_DIR)/Resources
PACKAGE_FRAMEWORKS_DIR := $(PACKAGE_CONTENTS_DIR)/Frameworks
PACKAGE_SHARED_FONTS_DIR := $(PACKAGE_RESOURCES_DIR)/shared/assets/fonts
PACKAGE_INFO_PLIST_SRC := tools/packaging/macos/Info.plist
PACKAGE_LAUNCHER_SRC := tools/packaging/macos/sketch-launcher
PACKAGE_DYLIB_BUNDLER := tools/packaging/macos/bundle-dylibs.sh
PACKAGE_LOCAL_ICON_DIR := tools/packaging/macos/local_app_icon
PACKAGE_APP_ICON_NAME := AppIcon
PACKAGE_APP_ICON_FILE := $(PACKAGE_APP_ICON_NAME).icns
PACKAGE_APP_ICON_SRC ?= $(PACKAGE_LOCAL_ICON_DIR)/$(PACKAGE_APP_ICON_FILE)
PACKAGE_APP_ICONSET_SRC ?= $(PACKAGE_LOCAL_ICON_DIR)/$(PACKAGE_APP_ICON_NAME).iconset
PACKAGE_BUNDLED_ICON_PATH := $(PACKAGE_RESOURCES_DIR)/$(PACKAGE_APP_ICON_FILE)
PACKAGE_ADHOC_SIGN_IDENTITY ?= -
DESKTOP_APP_DIR ?= $(HOME)/Desktop/$(PACKAGE_APP_NAME)
EXPORT_PRESET ?= data/last_session.pack
EXPORT_JSON ?= /tmp/drawing_program_snapshot_debug.json
WORKSPACE_PRESET ?= ../workspace_sandbox/data/presets/sketch_layout_v1.pack
PACKAGE_FONTS_SRC_PRIMARY := $(SHARED_VENDOR_DIR)/assets/fonts
PACKAGE_FONTS_SRC_WORKSPACE := $(SHARED_WORKSPACE_DIR)/assets/fonts
RELEASE_VERSION := $(strip $(shell cat "$(VERSION_FILE)" 2>/dev/null))
ifeq ($(RELEASE_VERSION),)
$(error Missing or empty VERSION file '$(VERSION_FILE)')
endif
RELEASE_DIR := build/release
RELEASE_BASENAME := $(RELEASE_PRODUCT_NAME)-$(RELEASE_VERSION)-$(RELEASE_PLATFORM)-$(RELEASE_ARCH)-$(RELEASE_CHANNEL)
RELEASE_APP_ZIP := $(RELEASE_DIR)/$(RELEASE_BASENAME).zip
RELEASE_APP_ZIP_SHA256 := $(RELEASE_APP_ZIP).sha256
RELEASE_MANIFEST := $(RELEASE_DIR)/$(RELEASE_BASENAME).manifest.txt
